name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # specify your .NET version

    - name: Restore dependencies
      run: dotnet restore
      working-directory: OutOfOffice/OutOfOffice # Adjust this path to your .NET project directory

    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: OutOfOffice/OutOfOffice # Adjust this path to your .NET project directory

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: OutOfOffice/OutOfOffice # Adjust this path to your .NET project directory

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x' # specify your Node.js version

    - name: Install dependencies
      run: npm install
      working-directory: front/out-of-office # Adjust this path to your front-end directory

    - name: Build
      run: CI=false npm run build
      working-directory: front/out-of-office # Adjust this path to your front-end directory

    - name: Test
      run: npm test
      working-directory: front/out-of-office # Adjust this path to your front-end directory
